BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: MR-NIRP
    DO_PREPROCESS: True              # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:  "C:\\Users\\kouts\\Desktop\\Thesis\\MR-NIRP\\garage_still_975"
    CACHED_PATH: "./data/PreprocessedData"  # Processed dataset save path, need to be updated
    PREPROCESS:
      USE_PSUEDO_PPG_LABEL: False
      LABEL_TYPE: 'DiffNormalized'
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: False
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 180
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BIGSMALL:
        BIG_DATA_TYPE: ['Standardized']
        SMALL_DATA_TYPE: ['DiffNormalized']
        RESIZE:
          BIG_H: 144
          BIG_W: 144
          SMALL_H: 9
          SMALL_W: 9
DEVICE: cpu
NUM_OF_GPU_TRAIN: 0
LOG:
  PATH: runs/exp
MODEL:
  NAME: BigSmall
  BIGSMALL:
    FRAME_DEPTH: 3
INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  MODEL_PATH: "./final_model_release/BP4D_BigSmall_Multitask_Fold3.pth"
