BASE: ['']
TOOLBOX_MODE: "unsupervised_method"      # "train_and_test"  or "only_test" or "unsupervised_method"
UNSUPERVISED:
  METHOD: ["ICA"]
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  OUTPUT_SAVE_DIR: "D:/MR-NIRP/data"
  DATA:
    FILTERING:
      USE_EXCLUSION_LIST: False
      EXCLUSION_LIST: [
        # Face detection failed:
        'subject2_driving_small_motion_940', 'subject16_driving_small_motion_940',
        'subject2_driving_still_940', 'subject4_driving_still_940', 'subject16_driving_still_940',
        'subject9_garage_small_motion_940',

        'subject6_garage_small_motion_975',

        'subject5_garage_still_975', 'subject6_garage_still_975', 'subject12_garage_still_940', 'subject12_garage_still_975',
      ]
      SELECT_TASKS: False
      TASK_LIST: ['subject12_garage_still_940', 'subject12_garage_still_975']
    FS: 30
    DATASET: MR-NIRP
    DO_PREPROCESS: True               # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH: "D:/MR-NIRP"                     # Raw dataset path, need to be updated
    CACHED_PATH: "D:/MR-NIRP/data/PreprocessedData_garage_small_motion"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "MR-NIRP_Raw_Raw_garage_small_motion"
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Raw
      DO_CHUNK: False
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.1
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
LOG:
  PATH: runs/exp_garage_small_motion
INFERENCE:
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10                 # In seconds
    # WINDOW_OVERLAP: 100             # In frames
